[workspace]

members = [
    "workspace.rs/backend"
  , "native"
  ]

[profile.release]
opt-level = 3
debug = false
overflow-checks = false
lto = "fat"
panic = 'abort'
incremental = false
codegen-units = 1
